### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by Mo-0hammed** [kaex/Insta-mass-account-creator#41]
When I run the file
And I put proxies in proxies.txt file

But it does not work

![notwork](https://user-images.githubusercontent.com/44713459/75385746-5edb1480-58f1-11ea-9ac1-0996df086f47.PNG)

**Comment by Mo-0hammed** [comment]
When I adjusted the file and placed
error_reporting(1);

The results are
PHP Fatal error:  Uncaught TypeError: Return value of autoloader::addNamespace() must be an instance of void, none returned in /root/Insta-mass-account-creator/src/autoloader.php:106
Stack trace:
#0 /root/Insta-mass-account-creator/start.php(7): autoloader->addNamespace('xosad\\', '/root/Insta-mas...')
#1 {main}
  thrown in /root/Insta-mass-account-creator/src/autoloader.php on line 106

**Comment by kaex** [comment]
git clone master and try again there is no issues.

**Comment by Mo-0hammed** [comment]
I git clone master and I got this error

**Comment by kaex** [comment]
Check line 7 in `start.php` in this repo and the one you have locally.

My code is working stable, don't make changes if you don't know what you're doing.
