### ISSUE TITLE
Not working and no output

### ISSUE THREAD

**Issue by nihatalim** [kaex/Insta-mass-account-creator#44]
Hello. I defined a file named proxies.txt and I put my socks proxyies like below:
  
socks5://10.11.12.13:8080
socks5://10.11.12.13:8081
socks5://10.11.12.13:8082
...
 
And I run start.php like below:
 
php start.php -l 5 -p proxies.txt
 
But there is no output after selecting 1 numbered selection.
 
Can you help me, please? Thank you.

**Comment by kaex** [comment]
Please use the proxies one per line without the `socks5://` e.g. `10.11.12.13:8080`
