### ISSUE TITLE
It may or may not

### ISSUE THREAD

**Issue by thsanki** [kaex/Insta-mass-account-creator#47]
if Me add already created account in
Account.json section and
Want to mass follow to another account 
Then this will work or not...
Please tell

**Comment by kaex** [comment]
Yes, it will work.

This is how you should add accounts to `accounts.json`

```json
[
  {
    "created": true,
    "username": "smallrabbit499krx",
    "password": "irHEmX7wnW7Yh8m",
    "email": "smallrabbit499krx@gmail.com",
    "name": "Marie-Theres Röhrs"
  },
  {
    "created": true,
    "username": "organicgoose462krx",
    "password": "irHEmX7wnW7Yh8m",
    "email": "organicgoose462krx@gmail.com",
    "name": "Kurt Gilbert"
  }
]
```

https://github.com/kaex/Insta-mass-account-creator/blob/da736d0a6faaa74752b17190bf78b8de1aa3b841/src/xosad/igGenerator.php#L304

and change line 304 to `'password' => $created['password'],`
