### ISSUE TITLE
Doesn't generate any accounts

### ISSUE THREAD

**Issue by OFFLYNE** [kaex/Insta-mass-account-creator#49]
![b5036bd48cca902a24a1af98da06e9f3](https://user-images.githubusercontent.com/46251448/80212197-58d68b00-8637-11ea-9165-4ad30e34cbe4.png)

**Comment by OFFLYNE** [comment]
it just returns to start, idk if im doing anything wrong

**Comment by babico** [comment]
I get the same response.

**Comment by kaex** [comment]
Show me your `proxy.txt` file.

**Comment by OFFLYNE** [comment]
[proxy.txt](https://github.com/kaex/Insta-mass-account-creator/files/4536529/proxy.txt)

**Comment by kaex** [comment]
Are you sure proxies are working? Try only `php start.php`
