### ISSUE TITLE
Account created but doesnt exist in instagram

### ISSUE THREAD

**Issue by bucol** [kaex/Insta-mass-account-creator#50]
Hello, i success created account but its not showing in instagram or cant login
Please fix this
![IMG_20200427_020523](https://user-images.githubusercontent.com/37924597/80317049-aca9c580-882b-11ea-9f7e-929af0916304.jpg)

**Comment by kaex** [comment]
Yes, I've run into that issue too i'm investigating it, Instagram creates the account but instantly deletes it after.

**Comment by kaex** [comment]
Follow issue #55
