### ISSUE TITLE
Valid Proxy File Yet No Account Created

### ISSUE THREAD

**Issue by tommy2049** [kaex/Insta-mass-account-creator#54]
Command ends with nothing in accounts.json file. Upon reading more than 99% of the issues here, everyone is running into the problem and the project owner is too rude to do something about it and just closes all the issues.

**Comment by niilopoutanen** [comment]
happens to me also

**Comment by kaex** [comment]
Too rude? Have you tried reading the issues here? They cannot even explain what they need and you are one of them too? Maybe start by showing me your proxy.txt and the command you use to start the bot then i'll maybe help you.

**Comment by tommy2049** [comment]
I used the proxy file from one of the issues here and you still haven't addressed his issue and it's been months ... If you actually addressed the previous issues there wouldn't be new ones ...

**Comment by kaex** [comment]
Your OS? and does anything return if you run it only with `php start.php` (after `php start.php` type `1` and hit enter

**Comment by kaex** [comment]
There is no answer, i am assuming it fixed your issue. labeled it with fixed, and your title `Valid Proxy File`, i see it wasn't that valid after all.
