### ISSUE TITLE
Invalid Project, RUDE Project Owner Won't Address Old Issues and Just Closes Them. I Recommend Using a Different Project to Everyone Here 

### ISSUE THREAD

**Issue by tommy2049** [kaex/Insta-mass-account-creator#56]
If you follow the instructions on here, the account won't be created and accounts.json will be empty. To make it worse the project owner is an absolute asshole leaving extremely rude comments. I read through all the old issues and 0 is resolved and the owner just closes them because he doesn't want to resolve the issues.

**Comment by kaex** [comment]
As you see this is my repo, you don't like this? Stop using this repository. If it was resolvable i would resolve it, you have zero knowledge of what's going with instagram and there updates. I'm going to continue talking to you on your other issue if you open another one you'll be banned. #54
