### ISSUE TITLE
How does it create accounts without spoofing browser fingerprints ?

### ISSUE THREAD

**Issue by ishandutta2007** [kaex/Insta-mass-account-creator#57]
It is well known that instagram blocks primary via browser fingerprinting, but I couldn't see any reference to canvas fingerprints or WebGL or Font fingerprints spoofing. @kaex This is not a ticket, but more of an FAQ, I was wondering if you can help me understand how the code works.

**Comment by GramCreator** [comment]
It uses web requests (solely for creating), it doesn't send any necessary background/log requests that are key for high success rates. It's definitely a useful tool, but only if your proxies can make up for the lack of "human behind a computer" detection.
