### ISSUE TITLE
Nothing is happening when I try and make an account and I've tried other people's fixes

### ISSUE THREAD

**Issue by ghost** [kaex/Insta-mass-account-creator#62]
I'm using Parrot OS, and using the code as instructed. It's not registering accounts, but I'm not getting any errors either. I appreciate lots of people have posted similar problems and not given much information so I've tried to add as much as possible. I've also tried anything that has fixed other people's problems. 

When I enter any variation of the command all I get is a screen stuck on "Generating Instagram Account!" Some of the commands I've tried

`
php start.php -l 5 -p prox.txt
sudo start.php
sudo start.php -l 5
php start.php
php start.php -l 5
php start.php -p prox.txt

`

My proxy file is this: https://pastebin.com/w4MqkG4e

I've tried routing through tor, using `sudo anonsurf start` and then running the php code without the -p command to see what'd happen, and that didn't work either.

I've tried changing the permissions for the .json file because I thought it might be that the accounts are being made but not written to the file but that isn't the case.

I've turned error reporting on for PHP, both in the .ini and in start.php but I'm not getting any errors

I've experimented with the content of prox.txt reducing the amount of proxies, and trying different proxies but that's not changed anything either. All the proxies are SOCKS5 too.

**Comment by kaex** [comment]
There is new updates on instagram. #55 Follow this issue i'll start updating this project soon.
