### ISSUE TITLE
Doesnt create new accounts it just says it does. But the account.json directory stays empty.

### ISSUE THREAD

**Issue by Borapipe** [kaex/Insta-mass-account-creator#65]
Doesn't create new accounts it just says it does. But the account.json directory stays empty.

**Comment by idrizdi** [comment]
After the register u must confirm email but this script doesn't it yet

**Comment by Borapipe** [comment]
What do you mean confirm email? There was no promor saying to do so. Nor was there any instruction saying how to.

**Comment by kaex** [comment]
@Borapipe @idrizdi, please follow #55
