### ISSUE TITLE
{} accounts.json empty

### ISSUE THREAD

**Issue by hk698** [kaex/Insta-mass-account-creator#68]
hello mate, 
Whenever I try to run the code, I followed the steps, but the accounts are not generating even if the message "Generating Instagram Account " is displaying. Any solution?

**Comment by rjsamra** [comment]
> hello mate,
> Whenever I try to run the code, I followed the steps, but the accounts are not generating even if the message "Generating Instagram Account " is displaying. Any solution?

Same Problem occurs here

**Comment by Gumbraise** [comment]
same

**Comment by almondWilde** [comment]
Same. Could it be because I'm not using SOCKS5? How can I ensure that SOCKS5 is working properly?

**Comment by Cuvaca** [comment]
hello, did anyone manage to make it work?

**Comment by ALT-F4-XD** [comment]
Samee

**Comment by kaex** [comment]
This project is no longer being maintained, if you want to make it work, update the requests with correct headers and post fields.
