### ISSUE TITLE
Can you point out the issue with the request?

### ISSUE THREAD

**Issue by xenaxon** [kaex/Insta-mass-account-creator#71]
Hello! Can you help me, by pointing out what the issue with the request is?

Or can I pay you to see what the issue is, and how to maintain this myself?

**Comment by kaex** [comment]
This project is no longer being maintained, if you want to make it work, update the requests with correct headers and post fields.

You can email me it's on my profile.

**Comment by xenaxon** [comment]
I messaged on your email: root@baransel.dev

**Comment by xenaxon** [comment]
Hello. I messaged you yesterday. did you receive my email?
