### ISSUE TITLE
the program doesn't work

### ISSUE THREAD

**Issue by davidj2003** [kaex/Insta-mass-account-creator#72]
i dont know what im doing wrong but the program just doesn't generate anything, and it doesn't give me an error either.
I put the proxies in the proxies.txt file and i try to run the program with php start.php -l 10 -p proxies.txt. the program says generating accounts and closes without generating anything. please help.

**Comment by kaex** [comment]
This project is no longer being maintained, if you want to make it work, update the requests with correct headers and post fields.
