### ISSUE TITLE
Crash when i chose to generate account

### ISSUE THREAD

**Issue by Kolhax** [kaex/Insta-mass-account-creator#79]
![image](https://user-images.githubusercontent.com/92904192/191166133-41100d82-04f1-47bb-96e4-8e6dd7470c53.png)

**Comment by Naster1202** [comment]
+

**Comment by ridhosatriawan** [comment]
yes my programs can't generate to

**Comment by VishavAulakh** [comment]
I am also facing the same issue

**Comment by ChristianOliveiraSilva** [comment]
Here is the same guys

**Comment by ChristianOliveiraSilva** [comment]
![image](https://user-images.githubusercontent.com/41245411/200438060-7ede5f3a-cdf7-450f-a76e-dc9e50e94be3.png)

**Comment by kaex** [comment]
Hello @Kolhax @Naster1202 @ridhosatriawan @VishavAulakh @ChristianOliveiraSilva, This tool is no longer being developed open-source. We are sorry. 😞

You can start by modifying the base with the updated headers and parameters.
